apiVersion: plugins.kubegems.io/v1beta1
kind: Plugin
metadata:
  name: global
  namespace: kubegems-installer
  annotations:
    plugins.kubegems.io/category: core/KubeGems
    plugins.kubegems.io/description: KubeGems global values.
spec:
  kind: template
  url: http://192.168.239.117:7899/
  chart: global
  version: "1.0.0"
  values:
    clusterName: "manager-cluster"
    # choose 'registry.cn-beijing.aliyuncs.com' or 'docker.io'
    imageRegistry: local
    imageRepository: "kubegems"
    storageClass: standard # change me to use a different storage class
    kubegemsVersion: v1.23.8
---
apiVersion: plugins.kubegems.io/v1beta1
kind: Plugin
metadata:
  name: kubegems
  namespace: kubegems-installer
  annotations:
    plugins.kubegems.io/category: core/KubeGems
    plugins.kubegems.io/description: KubeGems core service and dashboard.
spec:
  kind: helm
  url: http://192.168.239.117:7899/
  installNamespace: kubegems
  version: 1.23.8
  valuesFrom:
    - kind: ConfigMap
      name: "kubegems-global-values"
      prefix: "global."
